### ISSUE TITLE
Do not create war flag

### ISSUE THREAD

**Issue by JuuniorSantos** [ElgarL/Towny#153]
I've tried every way, putting flag war
even with op or not, not places.
as few hp of the town decreases
translate: google
Config:
  ############################################################
  # +------------------------------------------------------+ #
  # |                   Flag war settings                  | #
  # +------------------------------------------------------+ #
  ############################################################
 
  enemy:
    # If false, players won't be able to place war flags, effectively disabling warzones.
    allow_attacks: 'true'
    # If true, enemy's can only attack the edge plots of a town with war flags.
    only_attack_borders: 'true'
    # This many people must be online in target town in order to place a war flag in their domain.
    min_players_online_in_town: '0'
    # This many people must be online in target nation in order to place a war flag in their domain.
    min_players_online_in_nation: '0'
    max_active_flags_per_player: '1'
    flag:
      waiting_time: 1m
      # This is the block a player must place to trigger the attack event.
      base_block: fence
      # This is the block a player must place to trigger the attack event.
      light_block: torch
    beacon:
      # Must be smaller than half the size of town_block_size.
      radius: '3'
      # The range the beacon will be drawn in. It's flexibility is in case the flag is close to the height limit.
      # If a flag is too close to the height limit (lower than the minimum), it will not be drawn.
      height_above_flag:
        min: '3'
        max: '64'
      draw: 'true'
      wireframe_block: glowstone

**Comment by wjbolles** [comment]
I have had the same issue with the same settings. I attempted to change the block from fence post to other things but it had no effect.

**Comment by TekkitCommando** [comment]
Towny is being updated at the moment and if this a bug it should be fixed in the update :)

**Comment by wjbolles** [comment]
Seems to be because I was op'd. When I de-op'd myself the fence turns into a flag.

**Comment by mjcrafter100** [comment]
I have this problem, will see if a fresh install is in order

**Comment by dsnidr** [comment]
Has this been resolved, yet?

**Comment by ethsmith** [comment]
@Sniddunc I would check the latest towny version and see. :) I cannot tell you for sure. P.S. New issues go here: https://github.com/LlmDl/Towny if you want to reopen this over there if it is not resolved. Please make sure to search for the issue on the new repo before making a new issue so it does not get tagged with duplicate and closed.
