### ISSUE TITLE
Add support for UUIDs 

### ISSUE THREAD

**Issue by DuoDex** [ElgarL/Towny#154]
Basically, that.

**Comment by TekkitCommando** [comment]
UUID's For What, Ban Management plugins are at risk more than towny, that should be the focus for us bukkit devs right now :P However, Towny is being updated and what will be on there will be released eventually :)

**Comment by prodkid** [comment]
uuid support is needed if a player changes their name. If they do, their resident data gets reset.

**Comment by TekkitCommando** [comment]
This is a problem yes, but in the new update towny will more than likely be coded on the Sponge-Api and will fail to work on your Bukkit Server anyway. UUID support is something that should be added eventually

**Comment by alicheek** [comment]
bans are easily enough sorted through ip bans with the addition to username bans also they can only change their names every 30 days, a bigger issue is the case of players being no longer in their town due one changing ones name which if you run a server with towny is much more severe than the issue with banning.

**Comment by prodkid** [comment]
most ban plugins already have uuid support,  towny should as well.

**Comment by alicheek** [comment]
totally agree :)

**Comment by prodkid** [comment]
UUID was announced in october 2013, towny should have it by now, especially when changing your username is now available.

**Comment by thu2468** [comment]
Nope there no uuid compatibility yet

**Comment by prodkid** [comment]
We're aware it's  not compatible yet that's why this ticket was created

**Comment by TekkitCommando** [comment]
@alicheek ip bans dont solve much what if the banned player has siblings? and i would say that towny will have UUID support but you willl have to create a sponge server to use the updated towny

**Comment by alicheek** [comment]
One of my Admins are adding code for UUID support  for towny as we speak.

**Comment by TJ1632** [comment]
@ElgarL Please? The moment Mojang allowed name changes it caused some troubles.

**Comment by alicheek** [comment]
They have brought out an update to change the name of the players if they changed their names on the latest release

**Comment by prodkid** [comment]
@alicheek can you clarify ?

**Comment by alicheek** [comment]
One of my staff members has added code to the plug in which is the latest release of towny .

What this added is a command which will change the old username to the new username so they then have access to their town again , it's basically just a quick fix but it means at least there is a way for you to let people get their towns back

**Comment by alicheek** [comment]
The details should be on the change log

**Comment by prodkid** [comment]
Can I have a link?

**Comment by prodkid** [comment]
Would be too much to ask add support for 1.7.10?

**Comment by alicheek** [comment]
There is support it should be there on the latest Dev build

**Comment by prodkid** [comment]
I can only find towny 0.89.2.2 and it states its only for 1.8

**Comment by alicheek** [comment]
Should work for 1.7

**Comment by TekkitCommando** [comment]
Temp fixes dont solve anything as far as ElgarL is concerned Bukkit has outlived its usefulness and now Sponge is his interest, the plugin will be sponge when its updated and will NOT run on a bukkit server. Isn't it worth changing servers if you get to see towny grow?

**Comment by prodkid** [comment]
@TekkitCommando Yeah. I already have plans to move over to 1.8 with sponge but I run modded servers and depend on a handful of plugins as well so the transition will be rough one but will be so worth it :)

**Comment by LlmDl** [comment]
My git is now the official repo, there is already a renaming command.

**Comment by SullyTheUnusual** [comment]
@LlmDl Does your TownyNameUpdater automate the process, or do we still need to use "/ta resident <oldname> rename <newname>"?  I see that it only supports Towny v.0.89.2.2 which already claims this functionality?

**Comment by LlmDl** [comment]
TownyNameUpdater was written by backcab and does automate the process. It requires 0.89.2.2 or newer towny.
