### ISSUE TITLE
Towny fails to load file after Name Changing

### ISSUE THREAD

**Issue by prodkid** [ElgarL/Towny#155]
During restarts, towny fails to load file.
It's stuck on 
1:48:03 PM Towny: Enabling Towny v0.88.0.3
1:48:03 PM CONSOLE: [INFO] ==================== Towny ========================
I tried turning debugging on and seems to make no difference on giving me outputs.

**Comment by alicheek** [comment]
well you havent given the full log of the issue, so first off give the full debug log then some one can have a look at it

**Comment by prodkid** [comment]
There is no other information logged. Debug file empty and the log file in towny folder is unrelated.
as you can see here
http://pastebin.com/uR3PPk1D

**Comment by prodkid** [comment]
Is towny dead? Author has been inactive since Oct 22.

**Comment by ElgarL** [comment]
No its not dead. However Bukkit is.
We are focusing on a rewrite of Towny for Sponge.

**Comment by prodkid** [comment]
Would it be possible to investigate this issue? It's making towny unusable :/.

**Comment by prodkid** [comment]
Also, good to see :). We love your plugin.

**Comment by TekkitCommando** [comment]
@prodkid update your server to sponge to use towny update :)

**Comment by prodkid** [comment]
I'm using cauldron atm, sponge is not an option right now.

**Comment by TekkitCommando** [comment]
aww i see well sponge can do some amazing things and might replace cauldron as well :) @prodkid

**Comment by TekkitCommando** [comment]
i believe towny for sponge will be ready pretty soon :)

**Comment by prodkid** [comment]
@TekkitCommando the transition will be hard but we're looking forward to it.
Can I get some assistance on this ticket? Here's the backup that of the files that fails to load
https://www.dropbox.com/s/2lc8yrvuardvowp/2015-02-13%2012-18%20-%201423847929061.zip?dl=0
It is possible to debug towny and figure out what's the problem? Currently I have to restore to keep restoring from a backup from Feb 8.

**Comment by TekkitCommando** [comment]
Yep no problem let me have a look :)

**Comment by prodkid** [comment]
Anything yet?

**Comment by TekkitCommando** [comment]
oh sorry @prodkid went to work and forgot let me see

**Comment by TekkitCommando** [comment]
@prodkid is your towny debugger even on?

**Comment by TekkitCommando** [comment]
@prodkid theres no debugger enabled and your towny config is fu**ed up lol

**Comment by TekkitCommando** [comment]
theres options missing im pretty sure and theres over 60000 empty spaces and random #'s at random poiints

**Comment by TekkitCommando** [comment]
fix the config, enable debugger, send me the info then i can help you out buddy :)

**Comment by TekkitCommando** [comment]
if you need some extra help not through messages, send me a pm on bukkit dev and i will give you my skype id: http://dev.bukkit.org/profiles/TekkitCommando/

**Comment by prodkid** [comment]
Not sure how that happened with my config file but it's fixed now and debug is on. I messaged you on bukkit.

**Comment by TekkitCommando** [comment]
ok i added you to skype friend
