### ISSUE TITLE
Cant remove players from towns if they have underscores in their names.

### ISSUE THREAD

**Issue by Lovatoty** [ElgarL/Towny#159]
Mayors cant kick residents from towns if they have in underscore in their names. Using an underscore, Towny doesn't recognise the player, but using spaces, Towny recognises their name as two players. This makes the player unkickable. I should note that Towny recognises the name with the underscore as a registered player, but not a valid name, where as using a space or random gibberish, results in both an invalid name, and an error for a non-registered user.

If there is already a solution or workaround for this problem, I didn't see it in the documentation

**Comment by ethsmith** [comment]
I think your supposed to report your issue here friend ;) http://code.google.com/a/eclipselabs.org/p/towny/issues/entry?template=Defect%20report%20from%20user

**Comment by ElgarL** [comment]
Underscores are not legitimate characters in a players name.
