### ISSUE TITLE
Question: /plot toggle mobs or /town toggle mobs LIST

### ISSUE THREAD

**Issue by OscarGLorenz** [ElgarL/Towny#171]
Question: /plot toggle mobs or /town toggle mobs
¿Where is the list of entities blocked with that command?
¿Is possible to change it?

**Comment by ethsmith** [comment]
/t toggle mobs, I think it blocks all hostile mobs and I think you have to change it before the mod is compiled. Also go here https://github.com/LlmDl/Towny to post issues for now on :)

**Comment by OscarGLorenz** [comment]
Thanks

**Comment by ethsmith** [comment]
No problem
