### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by jsutaria** [ElgarL/Towny#175]
I believe the latest version of towny is 0.91.1.7, but the current one on the repo is 0.89.2.10. Can this be updated?

**Comment by leonardo-dgs** [comment]
@jsutaria ElgarL no longer develops the plugin, so this repository is discontinued, the version that you have seen is a fork developed by LlmDl, if you see on the site, there will be the link of the github page: https://github.com/TownyAdvanced/Towny

**Comment by ElgarL** [comment]
The current builds can always be found on http://towny.palmergames.com/

Llmdl updates Towny on his fork and uploads to the the website.
