### ISSUE TITLE
Towny Bug and Nation Spawn

### ISSUE THREAD

**Issue by payloss** [ElgarL/Towny#178]
Hi first off sorry if this is the wrong section when i /t unclaim on a outpost it unclaims but town can still teleport to it also i just wanted to know if there could anyway to add /n set spawn command for nation owners so all nation members can /n spawn thanks

**Comment by jordanwilliams1** [comment]
^^^

**Comment by jsuarezl** [comment]
The official towny issue tracker now is this https://github.com/LlmDl/Towny/issues
