### ISSUE TITLE
Some download link in build.xml has been not working 

### ISSUE THREAD

**Issue by TRLWeiss** [ElgarL/Towny#184]
When using the source code which you have released on github to build a jar file,there will be a crash because can't download the essential lib file.
Later I will send the detail download link to this issue.

**Comment by TRLWeiss** [comment]
<target name="download" depends="init">

		<get src="http://palmergames.com/libs/bukkit.jar" dest="${env.LIB}/bukkit.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/bpermissions.jar" dest="${env.LIB}/bpermissions.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/Essentials.jar" dest="${env.LIB}/Essentials.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/EssentialsGroupManager.jar" dest="${env.LIB}/EssentialsGroupManager.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/Permissions.jar" dest="${env.LIB}/Permissions.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/PermissionsEx.jar" dest="${env.LIB}/PermissionsEx.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/Register.jar" dest="${env.LIB}/Register.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/iConomy.jar" dest="${env.LIB}/iConomy.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/Questioner.jar" dest="${env.LIB}/Questioner.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/Vault.jar" dest="${env.LIB}/Vault.jar" skipexisting="true" />
		<get src="http://palmergames.com/libs/citizensapi-2.0-SNAPSHOT.jar" dest="${env.LIB}/citizensapi-2.0-SNAPSHOT.jar" skipexisting="true" />

http://palmergames.com/libs/
When open it there will be nothing to download.
I am not a native speaker in English so hope you can understand my meaning 😉Thanks

**Comment by ElgarL** [comment]
change the links to http://palmergames.com/data/libs/
You should be using the source from Llmdl now as he's maintaining Towny.
