### ISSUE TITLE
Plugin.yml in TownyChat.jar file setup incorrectly affecting townychat placeholders for chat plugins

### ISSUE THREAD

**Issue by axemwa** [ElgarL/Towny#187]
Plugin.yml in TownyChat.jar file setup incorrectly affecting townychat placeholders for chat plugins such as deluxechat, to fix this open the plugin.yml in the TownyChat.jar and change "name: Chat" to "name: TownyChat" at the top of the config of the plugin.yml for your future releases.

Fix was found by lunna123 and issue was reported by myself, refer to spigotmc forum page(https://www.spigotmc.org/goto/post?id=3065215#post-3065215) for more details.

**Comment by Androkai** [comment]
The really strange thing is that this line is/was always correct within the [source code](https://github.com/ElgarL/TownyChat/blob/master/src/plugin.yml#L1) here on GitHub, nobody ever changed it. It therefore looks as if this was done on purpose at building time or manually later.
Building it by myself it's still "TownyChat" within the plugin.yml.

**Comment by axemwa** [comment]
Fair enough just thought I'd report it anyway :) Should I mark this as closed then?

**Comment by Lunna123** [comment]
I just downloaded v. 0.52 from the file-repo and the issue is still present.(http://towny.palmergames.com/file-repo/TownyChat/0.52/)

So anyone that downloads TownyChat via the file-repo and doesn't build it themselves will encounter this issue.

**Comment by NorbiPeti** [comment]
Well, the maintained version is [here](https://github.com/TownyAdvanced/TownyChat) and that shows this as a change that happened accidentally as part of a refactor 5 months ago, which got fixed 4 months ago, but no release has been published since it looks like.
