### ISSUE TITLE
Using latest towny, players can claim plots within a WorldGuard region

### ISSUE THREAD

**Issue by axemwa** [ElgarL/Towny#190]
It as the title says, for some reason players can claim plots within WG regions is this something I can fix, towny devs can fix or worldguard can fix?

**Comment by axemwa** [comment]
I also noticed players can found/create a town within a worldguard region is there a setting for this in config or something worldguard needs to fix/update? 

I also made a suggestion to the worldguardextraflags author to add a WG flag that prevents town plots/homes from being claimed/founded for now but thought I'd ask you guys anyway just incase. Although I could just block those specfic commands for that region using WGEF which pretty much works the same

**Comment by axemwa** [comment]
If you make a fix for this too I suggest adding an option in config that allows server owners to set the radius of how far a town plot/home can be claimed/founded from a world guard region, pretty technical but very useful I think so that they cant claim just outside the border that way they can't just keep extending their plots over with region either

**Comment by Articdive** [comment]
#156 Please move your issue over to the correct fork of Towny. This fork is no longer maintained/not maintained for the time being.

https://github.com/LlmDl/Towny/issues?q=is%3Aopen+is%3Aissue

Please follow the link above to submit a ticket for Towny.

**Comment by axemwa** [comment]
oh whoops thanx! :)
